- name: Install Agent Dependencies
  hosts: all
  become: true
  tasks:
    - name: Install Python3 and pip
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask
      pip:
        name:
          - flask

- name: Deploy Agent
  hosts: all
  become: true
  tasks:
    - name: Upload Agent Script
      copy:
        src: ../agent/agent.py
        dest: /opt/init6/agent.py
        mode: '0755'

    - name: Upload Agent Service File
      copy:
        src: resources/agent.service
        dest: /etc/systemd/system/agent.service
        mode: '0644'

    - name: Reload Systemd Daemon
      shell: systemctl daemon-reload

    - name: Enable and Start Agent Service
      systemd:
        name: agent
        enabled: yes
        state: started

    - name: Reload Systemd Daemon
      shell: |
        touch /var/log/agent.log
        chmod 0777 /var/log/agent.log
