- name: Setup Nginx with SSL (for Packer)
  hosts: all
  become: true
  tasks:
    - name: Install Required Packages
      yum:
        name:
          - nginx
          - openssl
          - cronie
          - awscli
          - jq
        state: present

    - name: Ensure Cron Service is Enabled and Running
      systemd:
        name: crond
        enabled: yes
        state: started

    - name: Ensure required directories exist
      file:
        path: /etc/letsencrypt/live/war.pianka.io
        state: directory
        mode: '0755'

    - name: Upload SSL Certificate (fullchain.pem)
      copy:
        src: resources/fullchain.pem
        dest: /etc/letsencrypt/live/war.pianka.io/fullchain.pem
        owner: root
        group: root
        mode: '0644'

    - name: Upload SSL Private Key (privkey.pem)
      copy:
        src: resources/privkey.pem
        dest: /etc/letsencrypt/live/war.pianka.io/privkey.pem
        owner: root
        group: root
        mode: '0600'

    - name: Create Diffie-Hellman group
      command: openssl dhparam -out /etc/ssl/dhparam.pem 2048
      args:
        creates: /etc/ssl/dhparam.pem

    - name: Create Nginx configuration for war.pianka.io
      copy:
        dest: /etc/nginx/conf.d/war.pianka.io.conf
        content: |
          server {
              listen 80;
              server_name war.pianka.io;
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name war.pianka.io;

              ssl_certificate /etc/letsencrypt/live/war.pianka.io/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/war.pianka.io/privkey.pem;
              ssl_dhparam /etc/ssl/dhparam.pem;

              location / {
                  proxy_pass http://127.0.0.1:64808;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "Upgrade";
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }
          }

    - name: Ensure Nginx is enabled and started
      systemd:
        name: nginx
        enabled: yes
        state: restarted

    - name: Validate Nginx configuration
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0

    - name: Restart Nginx to Apply SSL
      systemd:
        name: nginx
        state: restarted
