- name: Setup Nginx with SSL (for Packer)
  hosts: all
  become: true
  tasks:
    - name: Install Required Packages
      yum:
        name:
          - nginx
          - certbot
          - python3-certbot-dns-route53
          - openssl
          - cronie
          - awscli
          - jq
        state: present

    - name: Ensure Cron Service is Enabled and Running
      systemd:
        name: crond
        enabled: yes
        state: started

    - name: Ensure required directories exist
      file:
        path: /etc/ssl/self-signed
        state: directory
        mode: '0755'

    - name: Generate a self-signed SSL certificate
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout /etc/ssl/self-signed/nginx-selfsigned.key
        -out /etc/ssl/self-signed/nginx-selfsigned.crt
        -subj "/CN=war.pianka.io"
      args:
        creates: /etc/ssl/self-signed/nginx-selfsigned.crt

    - name: Create a Diffie-Hellman group
      command: openssl dhparam -out /etc/ssl/self-signed/dhparam.pem 2048
      args:
        creates: /etc/ssl/self-signed/dhparam.pem

    - name: Create Nginx configuration for war.pianka.io
      copy:
        dest: /etc/nginx/conf.d/war.pianka.io.conf
        content: |
          server {
              listen 80;
              server_name war.pianka.io;
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name war.pianka.io;

              ssl_certificate /etc/ssl/self-signed/nginx-selfsigned.crt;
              ssl_certificate_key /etc/ssl/self-signed/nginx-selfsigned.key;
              ssl_dhparam /etc/ssl/self-signed/dhparam.pem;

              location / {
                  proxy_pass http://127.0.0.1:64808;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "Upgrade";
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }
          }

    - name: Ensure Nginx is enabled and started
      systemd:
        name: nginx
        enabled: yes
        state: restarted

    - name: Run Certbot for DNS Validation (During Packer Build)
      command: >
        certbot certonly --dns-route53 
        --dns-route53-propagation-seconds 30 
        -d war.pianka.io 
        --non-interactive --agree-tos 
        -m rick@pianka.io --debug
      register: certbot_result
      ignore_errors: yes

    - name: Fail if Certbot failed to generate a certificate
      fail:
        msg: "Certbot failed. Check /var/log/letsencrypt/letsencrypt.log."
      when: certbot_result.rc != 0

    - name: Update Nginx SSL Configuration with Certbot Certificates
      replace:
        path: /etc/nginx/conf.d/war.pianka.io.conf
        regexp: "/etc/ssl/self-signed/nginx-selfsigned.(crt|key)"
        replace: "/etc/letsencrypt/live/war.pianka.io/\\1"

    - name: Validate Nginx configuration
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0

    - name: Restart Nginx to Apply SSL
      systemd:
        name: nginx
        state: restarted
